# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.test_definition import TestDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestTestDefinition(unittest.TestCase):
    """TestDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestDefinition(self):
        """Test TestDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.test_definition.TestDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
