# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_accuracy_tests_api import CustomSpeechAccuracyTestsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechAccuracyTestsApi(unittest.TestCase):
    """CustomSpeechAccuracyTestsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_accuracy_tests_api.CustomSpeechAccuracyTestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_accuracy_test(self):
        """Test case for create_accuracy_test

        Creates a new accuracy test.  # noqa: E501
        """
        pass

    def test_delete_accuracy_test(self):
        """Test case for delete_accuracy_test

        Deletes the accuracy test identified by the given ID.  # noqa: E501
        """
        pass

    def test_get_accuracy_test(self):
        """Test case for get_accuracy_test

        Gets the accuracy test identified by the given ID.  # noqa: E501
        """
        pass

    def test_get_accuracy_tests(self):
        """Test case for get_accuracy_tests

        Gets the list of accuracy tests for the authenticated subscription.  # noqa: E501
        """
        pass

    def test_update_accuracy_test(self):
        """Test case for update_accuracy_test

        Updates the mutable details of the test identified by its id.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
