# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_endpoints_api import CustomSpeechEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechEndpointsApi(unittest.TestCase):
    """CustomSpeechEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_endpoints_api.CustomSpeechEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_endpoint(self):
        """Test case for create_endpoint

        Creates a new endpoint.  # noqa: E501
        """
        pass

    def test_create_endpoint_data_export(self):
        """Test case for create_endpoint_data_export

        Create a new endpoint data export task.  # noqa: E501
        """
        pass

    def test_delete_endpoint(self):
        """Test case for delete_endpoint

        Deletes the endpoint identified by the given ID.  # noqa: E501
        """
        pass

    def test_delete_endpoint_data(self):
        """Test case for delete_endpoint_data

        Deletes the transcriptions and captured audio files associated with the endpoint identified by the given ID.  # noqa: E501
        """
        pass

    def test_delete_endpoint_data_export(self):
        """Test case for delete_endpoint_data_export

        Deletes the endpoint data export task identified by the given ID.  # noqa: E501
        """
        pass

    def test_get_endpoint(self):
        """Test case for get_endpoint

        Gets the endpoint identified by the given ID.  # noqa: E501
        """
        pass

    def test_get_endpoint_data_export(self):
        """Test case for get_endpoint_data_export

        Gets the specified endpoint data export task for the authenticated user.  # noqa: E501
        """
        pass

    def test_get_endpoint_data_exports(self):
        """Test case for get_endpoint_data_exports

        Gets the list of endpoint data export tasks for the authenticated user.  # noqa: E501
        """
        pass

    def test_get_endpoints(self):
        """Test case for get_endpoints

        Gets the list of endpoints for the authenticated subscription.  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_endpoints(self):
        """Test case for get_supported_locales_for_endpoints

        Gets a list of supported locales for endpoint creations.  # noqa: E501
        """
        pass

    def test_update_endpoint(self):
        """Test case for update_endpoint

        Updates the metadata of the endpoint identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
