# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.test_update import TestUpdate  # noqa: E501
from swagger_client.rest import ApiException


class TestTestUpdate(unittest.TestCase):
    """TestUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestUpdate(self):
        """Test TestUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.test_update.TestUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
