# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.speech_model_definition import SpeechModelDefinition  # noqa: E501
from swagger_client.rest import ApiException


class TestSpeechModelDefinition(unittest.TestCase):
    """SpeechModelDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpeechModelDefinition(self):
        """Test SpeechModelDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.speech_model_definition.SpeechModelDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
