# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_models_api import CustomSpeechModelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechModelsApi(unittest.TestCase):
    """CustomSpeechModelsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_models_api.CustomSpeechModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_model(self):
        """Test case for create_model

        Creates a new model.  # noqa: E501
        """
        pass

    def test_delete_model(self):
        """Test case for delete_model

        Deletes the model identified by the given ID.  # noqa: E501
        """
        pass

    def test_get_model(self):
        """Test case for get_model

        Gets the model identified by the given ID.  # noqa: E501
        """
        pass

    def test_get_models(self):
        """Test case for get_models

        Gets the list of models for the authenticated subscription.  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_models(self):
        """Test case for get_supported_locales_for_models

        Gets a list of supported locales for model adaptation.  # noqa: E501
        """
        pass

    def test_update_model(self):
        """Test case for update_model

        Updates the metadata of the model identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
