from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from swagger_client.api.custom_speech_accuracy_tests_api import CustomSpeechAccuracyTestsApi
from swagger_client.api.custom_speech_datasets_for_model_adaptation_api import CustomSpeechDatasetsForModelAdaptationApi
from swagger_client.api.custom_speech_endpoints_api import CustomSpeechEndpointsApi
from swagger_client.api.custom_speech_models_api import CustomSpeechModelsApi
from swagger_client.api.custom_speech_transcriptions_api import CustomSpeechTranscriptionsApi
from swagger_client.api.service_health_api import ServiceHealthApi
