# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Endpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'concurrent_recognitions': 'int',
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'endpoint_urls': 'dict(str, str)',
        'endpoint_kind': 'str',
        'last_action_date_time': 'datetime',
        'status': 'str',
        'created_date_time': 'datetime',
        'content_logging_enabled': 'bool',
        'models': 'list[Model]',
        'locale': 'str',
        'properties': 'dict(str, str)'
    }

    attribute_map = {
        'concurrent_recognitions': 'concurrentRecognitions',
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'endpoint_urls': 'endpointUrls',
        'endpoint_kind': 'endpointKind',
        'last_action_date_time': 'lastActionDateTime',
        'status': 'status',
        'created_date_time': 'createdDateTime',
        'content_logging_enabled': 'contentLoggingEnabled',
        'models': 'models',
        'locale': 'locale',
        'properties': 'properties'
    }

    def __init__(self, concurrent_recognitions=None, id=None, name=None, description=None, endpoint_urls=None, endpoint_kind=None, last_action_date_time=None, status=None, created_date_time=None, content_logging_enabled=None, models=None, locale=None, properties=None):  # noqa: E501
        """Endpoint - a model defined in Swagger"""  # noqa: E501

        self._concurrent_recognitions = None
        self._id = None
        self._name = None
        self._description = None
        self._endpoint_urls = None
        self._endpoint_kind = None
        self._last_action_date_time = None
        self._status = None
        self._created_date_time = None
        self._content_logging_enabled = None
        self._models = None
        self._locale = None
        self._properties = None
        self.discriminator = None

        if concurrent_recognitions is not None:
            self.concurrent_recognitions = concurrent_recognitions
        self.id = id
        self.name = name
        if description is not None:
            self.description = description
        if endpoint_urls is not None:
            self.endpoint_urls = endpoint_urls
        self.endpoint_kind = endpoint_kind
        if last_action_date_time is not None:
            self.last_action_date_time = last_action_date_time
        if status is not None:
            self.status = status
        if created_date_time is not None:
            self.created_date_time = created_date_time
        if content_logging_enabled is not None:
            self.content_logging_enabled = content_logging_enabled
        self.models = models
        self.locale = locale
        if properties is not None:
            self.properties = properties

    @property
    def concurrent_recognitions(self):
        """Gets the concurrent_recognitions of this Endpoint.  # noqa: E501

        The number of concurrent recognitions the endpoint supports.  # noqa: E501

        :return: The concurrent_recognitions of this Endpoint.  # noqa: E501
        :rtype: int
        """
        return self._concurrent_recognitions

    @concurrent_recognitions.setter
    def concurrent_recognitions(self, concurrent_recognitions):
        """Sets the concurrent_recognitions of this Endpoint.

        The number of concurrent recognitions the endpoint supports.  # noqa: E501

        :param concurrent_recognitions: The concurrent_recognitions of this Endpoint.  # noqa: E501
        :type: int
        """

        self._concurrent_recognitions = concurrent_recognitions

    @property
    def id(self):
        """Gets the id of this Endpoint.  # noqa: E501

        The identifier of this entity.  # noqa: E501

        :return: The id of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Endpoint.

        The identifier of this entity.  # noqa: E501

        :param id: The id of this Endpoint.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Endpoint.  # noqa: E501

        The name of the object.  # noqa: E501

        :return: The name of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Endpoint.

        The name of the object.  # noqa: E501

        :param name: The name of this Endpoint.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this Endpoint.  # noqa: E501

        The description of the object.  # noqa: E501

        :return: The description of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Endpoint.

        The description of the object.  # noqa: E501

        :param description: The description of this Endpoint.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def endpoint_urls(self):
        """Gets the endpoint_urls of this Endpoint.  # noqa: E501

        The list of endpoint urls.  # noqa: E501

        :return: The endpoint_urls of this Endpoint.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._endpoint_urls

    @endpoint_urls.setter
    def endpoint_urls(self, endpoint_urls):
        """Sets the endpoint_urls of this Endpoint.

        The list of endpoint urls.  # noqa: E501

        :param endpoint_urls: The endpoint_urls of this Endpoint.  # noqa: E501
        :type: dict(str, str)
        """

        self._endpoint_urls = endpoint_urls

    @property
    def endpoint_kind(self):
        """Gets the endpoint_kind of this Endpoint.  # noqa: E501

        The kind of this endpoint (e.g. custom speech).  # noqa: E501

        :return: The endpoint_kind of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._endpoint_kind

    @endpoint_kind.setter
    def endpoint_kind(self, endpoint_kind):
        """Sets the endpoint_kind of this Endpoint.

        The kind of this endpoint (e.g. custom speech).  # noqa: E501

        :param endpoint_kind: The endpoint_kind of this Endpoint.  # noqa: E501
        :type: str
        """
        if endpoint_kind is None:
            raise ValueError("Invalid value for `endpoint_kind`, must not be `None`")  # noqa: E501
        allowed_values = ["SpeechRecognition", "LanguageIdentification", "PronunciationScore"]  # noqa: E501
        if endpoint_kind not in allowed_values:
            raise ValueError(
                "Invalid value for `endpoint_kind` ({0}), must be one of {1}"  # noqa: E501
                .format(endpoint_kind, allowed_values)
            )

        self._endpoint_kind = endpoint_kind

    @property
    def last_action_date_time(self):
        """Gets the last_action_date_time of this Endpoint.  # noqa: E501

        The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :return: The last_action_date_time of this Endpoint.  # noqa: E501
        :rtype: datetime
        """
        return self._last_action_date_time

    @last_action_date_time.setter
    def last_action_date_time(self, last_action_date_time):
        """Sets the last_action_date_time of this Endpoint.

        The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :param last_action_date_time: The last_action_date_time of this Endpoint.  # noqa: E501
        :type: datetime
        """

        self._last_action_date_time = last_action_date_time

    @property
    def status(self):
        """Gets the status of this Endpoint.  # noqa: E501

        The status of the object.  # noqa: E501

        :return: The status of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Endpoint.

        The status of the object.  # noqa: E501

        :param status: The status of this Endpoint.  # noqa: E501
        :type: str
        """
        allowed_values = ["NotStarted", "Running", "Succeeded", "Failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def created_date_time(self):
        """Gets the created_date_time of this Endpoint.  # noqa: E501

        The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :return: The created_date_time of this Endpoint.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time):
        """Sets the created_date_time of this Endpoint.

        The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :param created_date_time: The created_date_time of this Endpoint.  # noqa: E501
        :type: datetime
        """

        self._created_date_time = created_date_time

    @property
    def content_logging_enabled(self):
        """Gets the content_logging_enabled of this Endpoint.  # noqa: E501

        A value indicating whether content logging (audio &amp; transcriptions) is being used for a deployment.  # noqa: E501

        :return: The content_logging_enabled of this Endpoint.  # noqa: E501
        :rtype: bool
        """
        return self._content_logging_enabled

    @content_logging_enabled.setter
    def content_logging_enabled(self, content_logging_enabled):
        """Sets the content_logging_enabled of this Endpoint.

        A value indicating whether content logging (audio &amp; transcriptions) is being used for a deployment.  # noqa: E501

        :param content_logging_enabled: The content_logging_enabled of this Endpoint.  # noqa: E501
        :type: bool
        """

        self._content_logging_enabled = content_logging_enabled

    @property
    def models(self):
        """Gets the models of this Endpoint.  # noqa: E501

        Information about the deployed models.  # noqa: E501

        :return: The models of this Endpoint.  # noqa: E501
        :rtype: list[Model]
        """
        return self._models

    @models.setter
    def models(self, models):
        """Sets the models of this Endpoint.

        Information about the deployed models.  # noqa: E501

        :param models: The models of this Endpoint.  # noqa: E501
        :type: list[Model]
        """
        if models is None:
            raise ValueError("Invalid value for `models`, must not be `None`")  # noqa: E501

        self._models = models

    @property
    def locale(self):
        """Gets the locale of this Endpoint.  # noqa: E501

        The locale of the contained data.  # noqa: E501

        :return: The locale of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Endpoint.

        The locale of the contained data.  # noqa: E501

        :param locale: The locale of this Endpoint.  # noqa: E501
        :type: str
        """
        if locale is None:
            raise ValueError("Invalid value for `locale`, must not be `None`")  # noqa: E501

        self._locale = locale

    @property
    def properties(self):
        """Gets the properties of this Endpoint.  # noqa: E501

        The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.  # noqa: E501

        :return: The properties of this Endpoint.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this Endpoint.

        The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.  # noqa: E501

        :param properties: The properties of this Endpoint.  # noqa: E501
        :type: dict(str, str)
        """

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Endpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Endpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
