# coding: utf-8

"""
    Speech Services API v2.0

    Speech Services API v2.0.  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WebHookConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'web_url': 'str',
        'secret': 'str'
    }

    attribute_map = {
        'web_url': 'webUrl',
        'secret': 'secret'
    }

    def __init__(self, web_url=None, secret=None):  # noqa: E501
        """WebHookConfiguration - a model defined in Swagger"""  # noqa: E501

        self._web_url = None
        self._secret = None
        self.discriminator = None

        self.web_url = web_url
        if secret is not None:
            self.secret = secret

    @property
    def web_url(self):
        """Gets the web_url of this WebHookConfiguration.  # noqa: E501

        The registered URL that will be used to send the POST requests for the registered events to.  # noqa: E501

        :return: The web_url of this WebHookConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._web_url

    @web_url.setter
    def web_url(self, web_url):
        """Sets the web_url of this WebHookConfiguration.

        The registered URL that will be used to send the POST requests for the registered events to.  # noqa: E501

        :param web_url: The web_url of this WebHookConfiguration.  # noqa: E501
        :type: str
        """
        if web_url is None:
            raise ValueError("Invalid value for `web_url`, must not be `None`")  # noqa: E501

        self._web_url = web_url

    @property
    def secret(self):
        """Gets the secret of this WebHookConfiguration.  # noqa: E501

        A secret that will be used to create a SHA256 hash of the payload with the secret as HMAC key.  This hash will be set as X-MicrosoftSpeechServices-Signature header when calling back into the registered URL.  # noqa: E501

        :return: The secret of this WebHookConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this WebHookConfiguration.

        A secret that will be used to create a SHA256 hash of the payload with the secret as HMAC key.  This hash will be set as X-MicrosoftSpeechServices-Signature header when calling back into the registered URL.  # noqa: E501

        :param secret: The secret of this WebHookConfiguration.  # noqa: E501
        :type: str
        """

        self._secret = secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebHookConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebHookConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
