---
blank_issues_enabled: false
contact_links:
  - name: Exam AI-900: Microsoft Azure AI Fundamentals Community Support
    url: https://github.com/timothywarner/ai900/discussions
    about: Please ask and answer questions here.
